detect: {
  frame_id: "velodyne",

  sub_pc_topic: "/kitti/points_raw",
  #sub_pc_topic: "/fusion_points",
  sub_pc_queue_size: 1,

  pub_pc_ground_topic: "/segmenter/points_ground",
  pub_pc_nonground_topic: "/segmenter/points_nonground",
  pub_pc_clusters_topic: "/segmenter/points_clustered",

  ## Important to use roi filter for "Ground remover"
  #use_roi_filter: false,
  use_roi_filter: true,
  roi: {
    ## ROI range
    # type: true, float, float, float
    # default: 60.0,999.0,999.0 in SegMatch
    # default: "Cylinder"(0,60)
    roi_type: "Cylinder",
    #roi_type: "Square",
    # ROI filter needs lidar installed height
    roi_lidar_height_m: 1.73,
    ## Horizontal range
    #--- for "Cylinder"
    roi_radius_min_m: 2.,
    roi_radius_max_m: 120.,
    #--- for "Square"
    #roi_radius_min_m: 15.,
    #roi_radius_max_m: 120.,
    # Vertical range
    roi_height_below_m: 1.,
    roi_height_above_m: 20.,
  },

  ## Ground Segmenter
  # type: string
  # default: "GroundPlaneFittingSegmenter"
  ground_remover_type: "GroundPlaneFittingSegmenter",
  #ground_remover_type: "GroundRANSACSegmenter",
  ## Segment non-ground point cloud, otherwise, only Ground Segmenter
  # default: false
  use_non_ground_segmenter: true,
  #use_non_ground_segmenter: false,
  ## non-ground segmenter type
  # default: "RegionEuclideanSegmenter"
  non_ground_segmenter_type: "RegionEuclideanSegmenter",
  #non_ground_segmenter_type: "EuclideanSegmenter",
}